### PR TITLE
Add ability to make states public

### LINKED ISSUE #149: Allow a state to be public

### PR DESCRIPTION
**Pull request by JackWilb**
Closes #149

Waiting on some frontend changes here and on some testing

### CODE REVIEW

**Comment by JackWilb** [comment]
- [ ] Need to add `Switch` from material ui to creation screen with "public" label
- [ ] Need to update requests for PUT and POST state to use new params

**Comment by haihan-lin** [comment]
- [ ] Made the changes. 
- [ ] fixed the alerts (I think?). There should be success/failure alert at the bottom of the interface upon clicking confirm.
- [ ] The button also disables if there is no input for state name.

**Comment by JackWilb** [comment]
Things I noticed:
- no timeout for snack bar (can we add one so it doesn't just persist until closed?
- making state cleared the states list (on internal server error, works on success)

My TODOs:
- [ ] Test that public states are available to all
- [ ] Test that private states are not available to all

**Comment by haihan-lin** [comment]
the snacker timeout is a minute. maybe 5 seconds instead?

**Review by haihan-lin — APPROVED** [review]

**Pull request merged**
