### PR TITLE
Add additional medications and outcomes to the filters and the patient sidebar

### PR DESCRIPTION
**Pull request by JackWilb**
TODO:
- [x] Add anemia management (oral/iv iron) to the `patient_outcomes` route
- [x] Use anemia management information in the filters and sidebar
- [x] Add risk score to the filters and sidebar (include total LOS from that route, too)
- [x] Add outcome: ICU LOS (Already exists in sidebar as `Postoperative ICU Length of Stay`)
- [x] Add outcome: total LOS
- [ ] Show death as true + date of death if there is a date of death, false otherwise
- [ ] Add outcome: heart attack (Waiting for feedback from Ryan)
- [ ] Add outcome: revision
- [x] Add outcome: renal failure (Tons of codes for this)
- [ ] Get surgery case anemia data from the `hemoglobin` route to create filter and sidebar information
- [ ] Add outcome: Embolism, DVT, clots

### CODE REVIEW

**Comment by haihan-lin** [comment]
> Show death as true + date of death if there is a date of death, false otherwise

Is this entry available in any route?

**Comment by haihan-lin** [comment]
> Get surgery case anemia data from the hemoglobin route to create filter and sidebar information

This can be done directly by filtering Preop demo value. Or do we want just a chip option for anemic?

**Comment by JackWilb** [comment]
> > Show death as true + date of death if there is a date of death, false otherwise
> 
> Is this entry available in any route?

Death date comes back from `fetch_patient`

**Comment by JackWilb** [comment]
> > Get surgery case anemia data from the hemoglobin route to create filter and sidebar information
> 
> This can be done directly by filtering Preop hemo value. Or do we want just a chip option for anemic?

Yes, I think we should make a filter chip and show the value in the side panel where all the patient surgery data is

**Comment by haihan-lin** [comment]
> > > Get surgery case anemia data from the hemoglobin route to create filter and sidebar information
> > 
> > 
> > This can be done directly by filtering Preop hemo value. Or do we want just a chip option for anemic?
> 
> Yes, I think we should make a filter chip and show the value in the side panel where all the patient surgery data is

I'm adding this on the SANKEY branch since sankey diagram also needs this.

**Comment by JackWilb** [comment]
From todays meeting:

Do they have iron deficiency?
Do they have anemia?
Cause identified?
Were they treated?
Did they show up to surgery without anemia?

Hemo within one month of the start of surgery
Hemo on date of surgery

Ferritin is a test (good ferritin levels are 30ng/ml, less is deficiency) (make the label iron deficiency)
Patients can have iron deficiency without anemia

**Pull request closed without merging**
